version: '3'

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  
  #################-example-app-#####################
  example-app:
    build: ./db-app-example
    container_name: example-app
    volumes:
      - ./db-app-example:/usr/src/app
    
  ###################-POSTGRESQL-##########################
  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=proyecto
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/some_name/
    ports:
      - "5433:5432"

  kafka:
    image: "bitnami/kafka:latest"
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./commands:/commands
    depends_on:
      - zookeeper
    # me gustaría que cuando termine de levantarse por completo ejecute el siguiente comando sh /commands/init.sh
    #command: sh /commands/init.sh

  producer:
    build: ./producers
    container_name: producer_kafka
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - ./producers:/usr/src/app

  consumer:
    build: ./consumers
    container_name: consumer_kafka
    depends_on:
      - kafka
      - zookeeper
      - producer
    volumes:
      - ./consumers:/usr/src/app


